name: build_qrb5165_px4
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    container:
      image: rb5-flight-px4-build-docker:latest
    name: build
    steps:
      - run:
          /bin/bash clean.sh
          /bin/bash ci-tools/scripts/check-build-script.sh
          /bin/bash make_package.sh deb timestamp

