name: container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    
#    container:
#      image: rb5-flight-px4-build-docker:latest

    steps:
      - run: |
          docker run -v /repos:/ci-sandbox -w /ci-sandbox rb5-flight-px4-build-docker:latest ./build_pkg.sh
          
          git clone https://gitlab.com/voxl-public/voxl-sdk/services/voxl-px4.git
          ls voxl-px4
          
 #rm -r voxl-px4
 
  #        clean.sh
  #        build.sh
  #        make_package.sh
  #        run-docker.sh
          
          
          
          
          
#          /bin/bash clean.sh
#          /bin/bash ci-tools/scripts/check-build-script.sh
#          /bin/bash make_package.sh deb timestamp




#  steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
